(part "PTN09S2-H10120K1A"
    (packageRef "PTN09S2H10120K1A")
    (interface
        (port "1" (symbPinId 1) (portName "CCW1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "CCW2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "WIPER2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CW2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "COM") (portType INOUT))
        (port "8" (symbPinId 8) (portName "N.O.") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "PTN09S2-H10120K1A")
    (property "Description" "9.5 mm, Horizontal, Dual Section, Logarithmic, 10K, Through Hole, Knurled Shaft Rotary Potentiometer")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/ptn09sx.pdf")
    (property "symbolName1" "PTN09S2-H10120K1A")
)
